site_name: Documentation CUB Édimbourg
site_url: https://enzo-5.github.io/edimbourg/
docs_dir: docs
site_dir: site

theme:
  name: material
  language: fr
  logo: media/logo.png
  favicon: media/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: fr

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enzo-5

copyright: Licence CC 4.0 FR BY-NC-SA - 2025 Agence CUB Édimbourg

nav:
  - Accueil: index.md
  - CUB Édimbourg:
    - Documentations:
      - Introduction: documentation/introduction.md

      - Situations:
        - "Situation n°0 - Plan d'adressage": documentation/Situations/Situation_0.md
        - "Situation n°1 - Windows Server 2019": documentation/Situations/Situation_1.md
        - "Situation n°2 - Git": documentation/Situations/Situation_2.md
        - "Situation n°3 - PowerShell": documentation/Situations/PowerShell.md
        - "Situation n°4 - DHCP": documentation/Situations/Situation_DHCP.md
        - "Situation n°5 - Active Directory": documentation/Situations/Situation_5.md
        - "Situation n°6 - GPO & PKI": documentation/Situations/Situation_6.md

      - Cybersécurité:
        - "Situation n°1 - Analyse préalable": documentation/Cybersécurité/Cyber_Situation_1.md
        - "Situation n°2 - Pare-feu Stormshield": documentation/Cybersécurité/Cyber_Situation_2.md
        - "Situation n°3 - Routage et NAT": documentation/Cybersécurité/Cyber_Situation_3.md
        - "Situation n°4 - Cryptographie": documentation/Cybersécurité/Cyber_Situation_4.md
        - "Situation n°5 - Bastion": documentation/Cybersécurité/Cyber_Situation_5.md
        - "Situation n°6 - Filtrage protocolaire": documentation/Cybersécurité/Cyber_Situation_6.md
        - "Situation n°7 - SIEM Wazuh": documentation/Cybersécurité/Cyber_Situation_7.md

      - DNS:
        - "DNS Récursif": documentation/DNS/CUB - Serveur DNS Recursif.md
        - "DNS1 Récursif": documentation/DNS/CUB - Serveur DNS1 Récursif.md
        - "DNS Autorité": documentation/DNS/CUB - Serveur DNS Autorité.md
        - "DNS1 Esclave": documentation/DNS/CUB - Serveur DNS1 esclave.md

      - Configurations:
        - "Switch Niveau 2": documentation/Configurations/Situation_Switch_2.md
        - "Switch Niveau 3": documentation/Configurations/Situation_Switch_3.md
